apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: livelyfencing
type: Opaque
stringData:
  ENCRYPTION_KEY: "nOnXflSk4EeE2+mJLVGMlwF9Z+3sGm5ip/c0Lcj4wC0="
  CONNECTION_STRING: "Host=postgres;Port=5432;Database=livelyfencing;Username=lfuser;Password=0U5FUYSsfuwaeJdrDX7UIXXId1Q70Zc"
  SENDGRID_API_KEY: REPLACE_WITH_SENDGRID_KEY
  CF_TEAM_DOMAIN: REPLACE_WITH_CF_TEAM_DOMAIN
  CF_AUDIENCE: REPLACE_WITH_CF_AUDIENCE_TAG
