FROM node:22-alpine AS build
WORKDIR /app
COPY src/LivelyFencing.UI/package*.json ./
RUN npm install --quiet
COPY src/LivelyFencing.UI/ .
RUN npx ng build --configuration=production --output-path=/dist

FROM nginx:alpine AS runtime
COPY --from=build /dist/browser /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
