apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: livelyfencing
type: Opaque
stringData:
  POSTGRES_USER: lfuser
  POSTGRES_PASSWORD: "0U5FUYSsfuwaeJdrDX7UIXXId1Q70Zc"
  POSTGRES_DB: livelyfencing
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: livelyfencing
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
